import type { NextPage } from 'next'
import Head from 'next/head'
import BrowserComponent from '../components/browser'
import TestPerformanceComponent from '../components/TestPerformance'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Performance Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BrowserComponent/>

      <TestPerformanceComponent vendor={"AWS"}/>
      <TestPerformanceComponent vendor={"NCP"}/>

    </>
  )
}

export default Home
