import type { NextPage } from 'next'
import Head from 'next/head'
import { useCallback, useRef } from 'react';



const NCPObjectStorage: NextPage = () => {



  return (
    <>
      <Head>
        <title>NCP Object Storage Image Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      NCP Object Storage
      <div style={{
        "height":"500px"
      }}>
      </div>

    </>
  )
}

export default NCPObjectStorage;
